# Generated by Django 5.1.4 on 2024-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_id_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unique_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
