# Generated by Django 5.1.4 on 2024-12-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='unique_id',
        ),
        migrations.AddField(
    model_name='employee',
    name='id',
    field=models.AutoField(primary_key=True, default=1),
)
    ]
